version: '3.8'

services:
  finance_db:
    image: timescale/timescaledb:latest-pg17
    ports:
      - "5432:5432"
    volumes:
      - finance_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: user
      POSTGRES_DB: finance_db

  electricity_db:
    image: timescale/timescaledb:latest-pg17
    ports:
      - "5433:5432"
    volumes:
      - electricity_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: user
      POSTGRES_DB: electricity_db

  web:
    build: services/web
    ports:
      - "8000:8000"
    volumes:
      - ./services/web:/web
      - ./logger.py:/web/logger.py
      - ./tickers.py:/web/tickers.py
    depends_on:
      - finance
      - electricity
      - analyzer

  finance:
    build: services/finance
    ports:
      - "8005:8005"
    volumes:
      - ./services/finance:/finance
      - ./logger.py:/finance/logger.py
      - ./concrete:/finance/concrete
      - ./domain_objects:/finance/domain_objects
      - ./abstractions:/finance/abstractions
    depends_on:
      - finance_db

  electricity:
    build: services/electricity
    ports:
      - "8007:8007"
    volumes:
      - ./services/electricity:/electricity
      - ./logger.py:/electricity/logger.py
      - ./concrete:/electricity/concrete
      - ./domain_objects:/electricity/domain_objects
      - ./abstractions:/electricity/abstractions
    depends_on:
      - electricity_db

  updater:
    build: services/updater
    ports:
      - "8003:8003"
    volumes:
      - ./services/updater:/updater
      - ./logger.py:/updater/logger.py
      - ./tickers.py:/updater/tickers.py
    depends_on:
      - finance
      - electricity

  analyzer:
    build: services/analyzer
    ports:
      - "8004:8004"
    volumes:
      - ./services/analyzer:/analyzer
      - ./logger.py:/analyzer/logger.py
    depends_on:
      - finance
      - electricity

volumes:
  finance_data:
  electricity_data:
