services:

  web_service:
    build: services/web
    ports:
      - "8000:8000"
    volumes:
      - ./services/web:/web
      - ./logger.py:/web/logger.py
      - ./tickers.py:/web/tickers.py
    depends_on:
      - finance_db_service
      - analyzer_service

  moex_service:
    build: services/moex
    ports:
      - "8001:8001"
    volumes:
      - ./services/moex:/moex
      - ./logger.py:/moex/logger.py

  finance_db:
    image: timescale/timescalefinance_db:latest-pg17
    ports:
      - "5432:5432"
    volumes:
      - timeseries_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: user
      POSTGRES_DB: finance_db

  finance_db_service:
    build: services/finance_db
    ports:
      - "8002:8002"
    volumes:
      - ./services/finance_db:/finance_db_service
      - ./logger.py:/finance_db_service/logger.py
      - ./db_manager:/finance_db_service
    depends_on:
      - finance_db

  electricity_service:
    build: services/electricity
    ports:
      - "8007:8007"
    volumes:
      - ./services/electricity:/electricity
      - ./logger.py:/electricity/logger.py
    depends_on:
      - electricity_db_service

  electricity_db:
    image: timescale/timescalefinance_db:latest-pg17
    ports:
      - "5433:5433"
    volumes:
      - timeseries_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: user
      POSTGRES_DB: electricity_db

  electricity_db_service:
    build: services/electricity_db
    ports:
      - "8006:8006"
    volumes:
      - ./services/electricity_db:/electricity_db_service
      - ./logger.py:/electricity_db_service/logger.py
      - ./db_manager:/electricity_db_service
    depends_on:
      - electricity_db

  updater_service:
    build: services/updater
    ports:
      - "8003:8003"
    volumes:
      - ./services/updater:/updater
      - ./logger.py:/updater/logger.py
    depends_on:
      - moex_service
      - finance_db_service
      - electricity_service
      - electricity_db_service

  analyzer_service:
    build: services/analyzer
    ports:
      - "8004:8004"
    volumes:
      - ./services/analyzer:/analyzer
      - ./logger.py:/analyzer/logger.py
    depends_on:
      - finance_db_service
      - electricity_db_service

volumes:
  timeseries_data:
